language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
before_install:
- set -e
install:
- export CXX="g++-5"
- npm install
script:
- npm run coverage
notifications:
  slack:
    on:
      tags: true
    rooms:
    - secure: zCMYVLF7j8pZtQexDOuxCjNiE/nDstKS5PS0vagsrJuu7QPPOxMFqqXft6hJJ+Tu50t6sZND4hkOmL0qxKXlaSWwxRdIg3TWSfzVDR1sEpYz6+9dgyz7RFbHZ7Fp8SGmamPAMcWVOElU8x0NLCjpXMQ43EPTAp1CPRJEV3l/9IaSFX4fy+tJaWI+Vh56JwHL2OEfLhxo2fl4Uil04b/X3lILM1/P1SM/hxWzac8dXeOt6ztjbWwEJ/AqbMwzhl3U6/6qd5rN37HXsPRYKodARS7kKrzzBm/BbTe9NhA4IalrU29dXlZymA/KCxzFnMzJTqKNsdP46NcMoZ2MlLWskBopyxVnermPyK4rZzjFHtLBMZWDw6GdvChJpid8boCHxTSW/VNRMsX5gb3GO9gJrALBCRwR/PKJsaelpkvdcnoL82fPVfn3c4FlxNlmzNrADr++WLPndSuoB+5vnoMJUATsnn4ECG2/2/gXR5rdUeJaJTl9MJNOf/Z63bWci1wxH9AAUl0U5ADxbDkDaBjL3CIHf6QCRq0NTtS3nU6GyTciRCvGBC1cMZV2RvACvnj5CxzaEHak3dQbDqq5mJh4Etk2OXxJRaVwZQDMZYvWN25EQYMCZKGHgrhbfhlbnkcaGa7GMBHGrmgbpRajJirT62X55w5JaDlzJ58T5NO2oiM=

before_deploy:
  - npm install -g typescript

deploy:
  on:
    tags: true
  provider: npm
  email: jeromegn@gmail.com
  api_key:
    secure: YnAcALc2+5WOmjMg3nXcUeRbYuUTtJtbSaGlN5ytxLW6o4tmcqvUeXUV6QMF3HO3LPp0h7wFemN8OUVlwM8Ng6bV3s12zwy7n3K/DUPP6o9Q5ZiiXaXXl2NOkrZW/udvuUZuPR26er+ZzBwKGMC9VbqOr0m2iZfTyiQDMSE4ahugNm+/gwwYZGqlcnotXSTDuU64IBlyOLxW3gIVWVPlrRD52rcEgNzyUpxlXbXdAlpnvatzxNKgk6gP5DJGnd2/2wn9Dk/5WMA3OgrMiHZz/fr0gINHfq4ug3lz14J8zAOR3d51KmF4FPyNCCbylVAX4uFm3HTDIDmXXC0qE7qTG46IPfrk7Ui+qfIqX7smJUZ4S/kTKqe0e4IzCRVU7G9rj2b6bdfxHD1+CfL1s+DBSL78VgrpV3fo/U/Jy+0GjUGKEMO6GBib1C5vQpCpXDvtGsxsZCObGU934Tm9JsUAx0X0iN3+9xDSzfN52LLznhcwIw6R6jSUwJpR7mHQdJTsJfY/4aKJFBi5mzHr+YBVS0QPh6ZrIJmtYlXqA6k3/oPDw8xaQiefCW0BxKDvL5TgR21LVfcdwsJoq0BKB7VCAlOge/VKGtGv2EekkcY8q6oIzh1qor+oDQl5w1Nd8c8HKue9/b6dce8YbJxkXi70Wb99TuIlUPU63omUHACa48E=
